apiVersion: v1
kind: Service
metadata:
  name: stargate-svc
  namespace: stargate
  labels:
    app: stargate-app
spec:
  ports:
    - port: 8080
  selector:
    app: stargate-app
    tier: frontend
  type: LoadBalancer
