apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-sg-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  capacity:
    storage: 20Gi
  hostPath:
    path: /var/lib/mysql
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem

